<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>placo</name>
  <version>0.0.0</version>
  <description>Placo solver library</description>
  <maintainer email="ssam@skl.vc">user</maintainer>
  <license>MIT</license>

  <buildtool_depend>cmake</buildtool_depend>

  <depend>eigen</depend>
  <depend>pinocchio</depend>
  <depend>eiquadprog</depend>
  <depend>eigenpy</depend>
  <depend>libboost-python-dev</depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
